FROM node:14.17.5-alpine as builder
ENV DOCKER_BUILDKIT=1
WORKDIR /client
COPY package.json .
COPY package-lock.json .
RUN npm install --production
COPY . .
RUN npm run build

# Using nginx server
FROM nginx:1.21.3-alpine
ENV DOCKER_BUILDKIT=1
COPY --from=builder /client/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Using serve server
# FROM node:14.17.5-alpine
# RUN npm install -g serve
# COPY --from=builder /client/build /staticContent


