version: "3.8"

services:
    restapi:
        build: ./REST-Api
        depends_on:
            - database
        ports:
            - 5000:5000
        volumes:
            - ./REST-Api:/REST-Api
        environment:
            FLASK_ENV: development
            DB_USER: root
            DB_PASS: root
            DB_HOST: database
            DB_PORT: 3306
            DB_NAME: projectsmanager
            FLASK_APP: app
        command: gunicorn -w 4 -b 0.0.0.0:5000 app:app

    database:
        build: ./Database
        ports:
            - 3306:3306
        volumes:
            - projectsmanager-mariadb-data:/var/lib/mariadb

    client:
        build:
            context: ./client
            dockerfile: Dockerfile.production
        # depends_on:
        #     - restapi
        ports:
            - 80:80
        command: nginx -g "daemon off;"

# For populating de database with existing script run:
# docker exec -i database_image_id mysql  -uroot -proot projectsmanager < projectsManagerExportedDB.sql
volumes:
    projectsmanager-mariadb-data:
